/*
 * Second attempt VGA bitgen - Draw squares statically.
 *
 * Currently draws five rectangles of different, questionably 
 *   colored rectangles on the screen. I've changed it so that 
 *   rgb is a proper 24-bit color.  
 *
 * inputs:
 *		vga_blank_n - "bright" signal meaning we're drawing to the screen.
 *		hcount - current hcount generated by vga_control. Includes front porch,
 *					so it should be offset by 158 pixels to get corresponding pixel.
 *    vcount - current vcount generated by vga_control.
 *
 * outputs:
 *		rgb - 24-bit color. Arranged from MSB to LSB: RR GG BB
 */
module bitgen2 (vga_blank_n, hcount, vcount, rgb);
	input vga_blank_n;
	input [9:0] hcount, vcount;
	output [23:0] rgb;

	reg [7:0] r, g, b;
	assign rgb = {r, g, b};
	
	wire [9:0] x_pos, y_pos;
	assign x_pos = hcount - 10'd158;
	assign y_pos = vcount;
	
	
	always@(*) begin
		{r, g, b} = 0;
		
		if(vga_blank_n) 
		begin		
			// Draw a 100x100 square @ (0,0)
			if(x_pos >= 0 && x_pos < 100 && y_pos >= 0 && y_pos < 100)
			begin
				r = 8'h00;
				g = 8'h00;
				b = 8'h80;
			end
			
			// Draw a 100x200 rect at top-right corner.
			else if(x_pos >= 540 && x_pos < 640 && y_pos >= 0 && y_pos < 200)
			begin
				r = 8'hFF;
				g = 8'hFF;
				b = 8'hFF;
			end
			
			// Draw a 500x100 rect @ bottom-left corner.
			else if(x_pos >= 0 && x_pos < 500 && y_pos >= 380 && y_pos < 480)
			begin
				r = 8'h00;
				g = 8'hFF;
				b = 8'h00;
			end
			
			// Draw a 100x100 rect @ bottom-right corner.
			else if(x_pos >= 539 && x_pos < 640 && y_pos >= 379 && y_pos < 480)
			begin
				r = 8'h4B;
				g = 8'h5F;
				b = 8'h81;
			end
			
			// Draw a 50x50 rect @ (100,100)
			else if(x_pos >= 100 && x_pos < 150 && y_pos >= 100 && y_pos < 150)
			begin
				r = 8'hFF;
				g = 8'hFF;
				b = 8'h00;			
			end
			
		   // background
			else
			begin
				r = 8'h32;
				g = 8'h17;
				b = 8'h4D;			
			end
		end
	end
	
	
endmodule
